### ISSUE TITLE
Like button

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#1182]
### Details

An animated like button

### Screenshots

![Screenshot 2023-06-10 082312](https://github.com/Spyware007/Animating-Buttons/assets/106100728/5bd90749-3e19-4578-bc4d-56a5c3274e16)
![Screenshot 2023-06-10 082325](https://github.com/Spyware007/Animating-Buttons/assets/106100728/6640db8d-40bd-4df0-8ed2-07df472ea4c3)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Hello @Souravvmishra, can you take look at the issues created by me ?

Because it was created 4 days ago, please make sure to assign me so that i can make further progress!

Here's the link: https://github.com/Spyware007/Animating-Buttons/issues/created_by/0xabdulkhalid

**Comment by Souravvmishra** [comment]
The Link Doesn't Seems Working, Please Mention The Issue Number

**Comment by 0xabdulkhalid** [comment]
No @Souravvmishra, try it once again

You can see the issues created by me one by one, here's the preview
![image](https://github.com/Spyware007/Animating-Buttons/assets/92252895/2d20f1f4-714e-4344-92de-fac251753b4d)

You can assign every one of them, because i want to contribute more buttons to this repository.

So please consider to assign me, I will able to make the PR's for every issues within 1hr.

**Comment by Spyware007** [comment]
# Please check #1346
