### ISSUE TITLE
Missing PR Template

### ISSUE THREAD

**Issue by Anshika-Jain02** [Spyware007/Animating-Buttons#911]
Hi there!

*I recommend adding the Pull Request Template to improve clarity and make it easier for new contributors.*

Please assign this issue to me under GSSoC'23 @Spyware007

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by Anshika-Jain02** [comment]
@sagnik-p can you please stop spamming all my issues with these messages and find your issues. I am working on this

**Comment by Anshika-Jain02** [comment]
@TANYA-CHAN please assign this issue to me as i have opened this issue.

**Comment by sagnik-p** [comment]
Hi!
Its been more than a week since the issue was assigned to you
Hi!
It doesn't seem like you are working on it and there has been no update
Why should others wait while you keep your "seat" reserved?
Thanks for understanding

**Comment by sagnik-p** [comment]
Hi!
Its been more than a week since the issue WAS assigned to YOU
It doesn't seem like you are working on it and there has been no update
Why should others wait while you keep your "seat" reserved.?
Thanks for understanding

**Comment by Anshika-Jain02** [comment]
@sagnik-p there is no time limit and the mentor will decide it. I am working on these issues and already created PR for all issues you mentioned earlier but you keep spamming on all issues and its been only 5 days.

**Comment by sagnik-p** [comment]
True, there is no time limit . I agree with you on that

You said that you have submitted PRs for your issues, well either you haven't  or you have not referenced the PR properly , otherwise this thread should have been closed automatically
It this thread had the correct references, I would not ask the collaborator/owner to assign this issue to me

And yes , I am asking to work on those issues that have been assigned a long time before like 8 days

Have you started working on this issue?
Or you "will start soon"

I think I would be able to complete it soon

Thanks for understanding

**Comment by Akanksha-202** [comment]
@Anshika-Jain02 you can start working on this issue

**Comment by Anshika-Jain02** [comment]
@Akanksha-202 Ma'am, I can see that the pull request template was already added in the previous week around the time when I raised this issue, but I can't see any closed issues or PR under which that work was done. So, what should I do now?

**Comment by Akanksha-202** [comment]
This issue is now closed ! Nothing needs to be done 
@Anshika-Jain02
